Tracker:AddLocations("locations/1st market.json")
Tracker:AddLocations("locations/2nd market.json")
Tracker:AddLocations("locations/3rd market.json")
Tracker:AddLocations("locations/4th market.json")
Tracker:AddLocations("locations/5th market.json")
Tracker:AddLocations("locations/6th market.json")
Tracker:AddLocations("locations/ability card dex.json")
Tracker:AddLocations("locations/challenge market.json")
Tracker:AddLocations("locations/end of market.json")
Tracker:AddLocations("locations/market card reward.json")
Tracker:AddLocations("locations/tutorial.json")
Tracker:AddLocations("locations/Overworld.json")
